import { Button } from "std-widgets.slint";

export struct ButtonData {
    image: image,
    color: color,
}

export component IconButton {
    callback clicked();
    in property <image> icon;
    in property <color> icon-color: black;
    in property <length> icon-size: 24px;
    in property <length> button-width: 60px;
    in property <length> button-height: 60px;

    width: root.button-width;
    height: root.button-height;

    TouchArea {
        clicked => { root.clicked() }

        Rectangle {
            width: 100%;
            height: 100%;
            border-radius: 4px;
            border-width: 1px;
            border-color: #2879fc;
            background: parent.has-hover ? #2e2e2e : #292929;

            Image {
                source: root.icon;
                colorize: root.icon-color;
                width: root.icon-size;
                height: root.icon-size;
            }
        }
    }
}
