[package]
name = "stream_deck"
build = "build.rs"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1.17.1"
image = { version = "0.25.10" }
chrono = "0.4.45"
chrono-tz = "0.10.4"
windows = { version = "0.62.2", features = [
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Foundation",
] }

[build-dependencies]
slint-build = "1.17.1"
