version: "0.2"
ignorePaths:
  - .gitignore
  - Cargo.toml
  - Cargo.lock
dictionaryDefinitions: []
dictionaries: []
words:
  - Flickable
  - KEYBD
  - KEYBDINPUT
  - KEYEVENTF_KEYUP
  - slint
ignoreWords: []
import: []
