import { VerticalBox, Button } from "std-widgets.slint";
import { Clock } from "../components/clock/clock.slint";

export component HomePage {
    callback next_screen();

    in property <string> current-time;

    TouchArea {
        width: 100%;
        height: 100%;
        clicked => { root.next_screen(); }

        Image {

            Clock {
                current-time: root.current-time;
            }

            width: 100%;
            height: 100%;
            image-fit: fill;
            source: @image-url("../../assets/test.png");
        }
    }
}
