import { VerticalBox, Button } from "std-widgets.slint";
import { IconButton } from "../components/icon_button/icon_button.slint";

export component SecondPage {
    callback back();
    callback key-pressed(int);

    GridLayout {
        padding: 5px;
        spacing: 2px;
        Row {
            IconButton {
                icon: @image-url("../../assets/uil--clock.svg");
                icon-color: #4287f5;
                icon-size: 32px;
                clicked => { root.back() }
            }

            IconButton {
                icon: @image-url("../../assets/ic--baseline-plus.svg");
                icon-color: #4287f5;
                icon-size: 32px;
                clicked => { root.key-pressed(2); }
            }

            IconButton {
                icon: @image-url("../../assets/material-symbols--skip-next.svg");
                icon-color: #4287f5;
                icon-size: 32px;
                clicked => { root.key-pressed(3); }
            }
        }

        Row {
            IconButton {
                icon: @image-url("../../assets/mdi-light--image.svg");
                icon-color: #4287f5;
                icon-size: 32px;
                clicked => { root.key-pressed(4); }
            }

            IconButton {
                icon: @image-url("../../assets/icon-park-outline--change.svg");
                icon-color: #4287f5;
                icon-size: 32px;
                clicked => { root.key-pressed(5); }
            }

            IconButton {
                icon: @image-url("../../assets/ion--bulb-outline.svg");
                icon-color: #4287f5;
                icon-size: 32px;
                clicked => { root.key-pressed(6); }
            }
        }
    }
}
