import { VerticalBox, Button } from "std-widgets.slint";
export component TestComponent {
    property <bool> open: true;

    VerticalBox {
        label := Text {
            text: "Button not clicked";
        }

        Button {
            text: "Click me";
            clicked => {
                label.text = "Btn clicked";
                open = false;
                debug(open)
            }
        }
    }
}
