import { HomePage } from "../pages/home_page.slint";
import { SecondPage } from "../pages//second_page.slint";
import { ButtonData } from "../components/icon_button/icon_button.slint";

export component MainWindow inherits Window {
    title: "Stream Deck";
    preferred-width: 320px;
    preferred-height: 240px;

    in-out property <int> current-page: 0;
    in property <string> current-time;
    in property <[ButtonData]> buttons;
    callback key-pressed(int);

    Rectangle {
        clip: true;
        width: 100%;
        height: 100%;
        background: #1d1d1d;

        VerticalLayout {
            y: root.current-page == 0 ? 0 : -root.height;

            animate y {
                duration: 250ms;
                easing: ease-in-out;
            }

            HomePage {
                width: root.width;
                height: root.height;
                current-time: root.current-time;
                next_screen => { root.current-page = 1; }
            }

            SecondPage {
                width: root.width;
                height: root.height;
                buttons: root.buttons;
                back => { root.current-page = 0; }
                key-pressed(id) => { root.key-pressed(id); }
            }
        }
    }
}
