import { HomePage } from "../components/home_page.slint";
import { SecondPage } from "../components/second_page.slint";

export component MainWindow inherits Window {
    title: "Stream Deck";
    preferred-width: 320px;
    preferred-height: 240px;

    property <int> current_page: 0;

    if root.current_page == 0: HomePage {
        width: 100%;
        height: 100%;
        next_screen => { root.current_page = 1; }
    }

    if root.current_page == 1: SecondPage {
        back => { root.current_page = 0; }
    }
}
